# Generated by Django 2.2.6 on 2019-10-08 11:20
import json

from django.db import migrations

import wagtail.core.blocks
from wagtail.core.blocks.stream_block import StreamValue
import wagtail.core.fields



def forwards(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")

    pages = HomePage.objects.all()
    for page in pages:
        stream_data = page.body.stream_data
        for block in stream_data:
            if block["type"] == "title":
                block["type"] = "heading"

        stream_block = page.body.stream_block
        page.body = StreamValue(stream_block, [], is_lazy=True, raw_text=json.dumps(stream_data))
        page.save()

def backwards(apps, schema_editor):
    # TODO
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
