# Generated by Django 2.2.6 on 2019-10-08 11:20
import json

from django.db import migrations

import wagtail.core.blocks
import wagtail.core.fields

from wagtailstreamfieldmigrate import StreamfieldMigration

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
    ]

    def forwards(stream_data):
        for block in stream_data:
            if block["type"] == "title":
                block["type"] = "heading"
        return stream_data

    def backwards(stream_data):
        # TODO
        return stream_data

    operations = [
        StreamfieldMigration('home', 'homepage', 'body', forwards, backwards),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
